BASE_INCLUDE = -I/usr/local/include -I/usr/integration_server_third/include

BASE_LIB_PATH = -L/usr/lib/x86_64-linux-gnu -L/usr/integration_server_third/lib

BASE_LIB = -lpthread

CXX = g++

VERSION = -O0

CXXFLAGS = -Wall -std=c++11 -g
