BASE_INCLUDE = -I/usr/local/include -I/usr/local/integration_server_third/include

ZDB_INCLUDE = -I/usr/local/integration_server_third/include/zdb

BASE_LIB_PATH = -L/usr/lib/x86_64-linux-gnu -L/usr/local/integration_server_third/lib

ASAN_LIB = -lasan

BASE_LIB = -lpthread

CXX = g++

VERSION = -O0

#内存检测开启
ASAN = -fsanitize=address

CXXFLAGS = -Wall -std=c++11 -g
